name: OSV Scanner

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  scan-pr:
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@c51854704019a247608d928f370c98740469d4b5" # v2.3.5

  scan-scheduled:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c51854704019a247608d928f370c98740469d4b5" # v2.3.5
